# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('case_no', models.IntegerField(unique=True)),
                ('filling_date', models.DateField()),
                ('appearing_lawyer', models.CharField(max_length=500)),
                ('opposite_lawyer', models.CharField(blank=True, max_length=500)),
                ('fees', models.FloatField(blank=True, default=0.0)),
                ('remarks', models.TextField(blank=True)),
                ('prev_date', models.DateField()),
                ('next_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('history', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advocate.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CourtOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company', models.CharField(max_length=250)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advocate.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advocate.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advocate.State'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advocate.CaseStage'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advocate.CaseType'),
        ),
        migrations.AddField(
            model_name='case',
            name='court_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advocate.CourtOf'),
        ),
    ]
