# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='case',
            name='fav',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
