# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0002_auto_20160810_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='company',
            new_name='company_name',
        ),
    ]
