# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0003_auto_20160815_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
