# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0004_auto_20160815_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advocate.City'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advocate.State'),
        ),
    ]
