# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Advocate', '0006_auto_20160815_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='username',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
