# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0008_auto_20160817_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
