# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0011_case_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='confirmation',
            field=models.CharField(choices=[(0, 'Canceled'), (1, 'Pending'), (2, 'Confirmed')], default=1, max_length=10),
        ),
    ]
