# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0013_auto_20160904_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='confirmation',
            field=models.CharField(choices=[('Canceled', 0), ('Pending', 1), ('Confirmed', 1)], default=1, editable=False, max_length=10),
        ),
    ]
