# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0014_auto_20160904_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='confirmation',
            field=models.CharField(choices=[(0, 'Canceled'), (1, 'Pending'), (2, 'Confirmed')], default='Pending', editable=False, max_length=10),
        ),
    ]
