# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0018_auto_20160904_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_stage',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_of',
        ),
        migrations.RemoveField(
            model_name='casehistory',
            name='case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseHistory',
        ),
    ]
