# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0021_case_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='party_name',
            field=models.CharField(max_length=100),
        ),
    ]
