# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0024_case_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='advocate',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Advocate.SiteUser'),
        ),
    ]
