# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0025_auto_20160906_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
